# Generated by Django 4.2.15 on 2025-11-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
