# Generated by Django 4.2.15 on 2025-12-01 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='meta_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Meta de ventas mensual', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='comision_monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada')], default='Pagada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
